#!/usr/bin/env bash

usage() {
  echo "hashname <filename>"
  exit 1
}

[[ -z "$1" ]] && usage

hash=$(sha1sum "$1" | awk '{ print $1 }')
hashlen=${2:-16}
shorthash=${hash:0:$hashlen}
filename=$(basename "$1")

case $filename in
  *.*)
    ext="${filename##*.}";
    sfilename="${shorthash}.${ext}"
    ;;
  *)
    sfilename="${shorthash}"
esac

echo $sfilename

