#!/usr/bin/env bash
hash=$(sha1sum "$1" | awk '{ print $1 }')
hashlen=${2:-16}
shorthash=${hash:0:$hashlen}
filename=$(basename "$1")
if [[ $filename == *.* ]]; then
  ext="${filename##*.}"
  sfilename="${shorthash}.${ext}"
else
  sfilename="${shorthash}"
fi
echo $sfilename
