#!/usr/bin/env bash

hash=$(sha1sum "$1" | awk '{ print $1 }')
hashlen=${2:-16}
shorthash=${hash:0:$hashlen}
filename=$(basename "$1")

case $filename in
  *.*)
    ext="${filename##*.}";
    sfilename="${shorthash}.${ext}"
    ;;
  *)
    sfilename="${shorthash}"
esac

echo $sfilename
